spring.application.name=auth
server.port = 8081
#Database Resources

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/wow_product_service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql= true


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
server.servlet.context-path=/wow/auth/api


spring.jackson.default-property-inclusion=NON_NULL